title: "Nikhil Yadav"
description: "Research Project Associate"
logo: "/assets/images/profile.png" # (optional) Add a profile picture
theme: jekyll-theme-cayman
minimal_mistakes_skin: default

# Site Navigation
navigation:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Outreach"
    url: /outreach/
  - title: "Co-curriculars"
    url: /co-curriculars/
  - title: "Bio"
    url: /bio/

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
